-- ALTER TABLE users ADD column is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE users MODIFY COLUMN name VARCHAR(150);

ALTER TABLE users MODIFY COLUMN email VARCHAR(100) AFTER id;
ALTER TABLE users MODIFY COLUMN created_at TIMESTAMP FIRST; 
SELECT * from users;  
